/*
 * MelySig - Geolocalisation de points d'interets sur vos endroits favoris !
 * MelySig est systeme d'information geographique qui animera vos decouvertes du monde :)
 * Copyright 2014 - melysig.exia-nancy.com
 * Auteurs : Pocecco Julien, Mougenel Gerold, Gaudenot Guillaume & Robert Sebastien.
 */
package fr.melysig.vues;

import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author Sébastien
 */
public class ActualitesNew extends javax.swing.JFrame {

    /**
     * Creates new form ActualitesNew
     */
    public ActualitesNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHaut = new javax.swing.JPanel();
        panelContenu = new javax.swing.JPanel();
        monTexteDeBienvenue = new javax.swing.JLabel();
        monLabelActualiteSelectionne = new javax.swing.JLabel();
        monPanelDefilantActualites = new javax.swing.JScrollPane();
        maListeActualites = new javax.swing.JList();
        monLabelDernieresActualites = new javax.swing.JLabel();
        monPanelDefilantDescriptionActualite = new javax.swing.JScrollPane();
        maDescriptionActualite = new javax.swing.JTextArea();
        monLibelleActualite = new javax.swing.JTextField();
        monBoutonModifier = new javax.swing.JButton();
        monBoutonAjouter = new javax.swing.JButton();
        monBoutonSupprimer = new javax.swing.JButton();
        monLabelStatistiques = new javax.swing.JLabel();
        mesStatistiques = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 750));
        setPreferredSize(new java.awt.Dimension(900, 750));
        getContentPane().setLayout(null);

        panelHaut.setBackground(new java.awt.Color(204, 255, 102));

        javax.swing.GroupLayout panelHautLayout = new javax.swing.GroupLayout(panelHaut);
        panelHaut.setLayout(panelHautLayout);
        panelHautLayout.setHorizontalGroup(
            panelHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panelHautLayout.setVerticalGroup(
            panelHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(panelHaut);
        panelHaut.setBounds(0, 0, 900, 70);

        panelContenu.setOpaque(false);

        monTexteDeBienvenue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monTexteDeBienvenue.setForeground(new java.awt.Color(255, 255, 0));
        monTexteDeBienvenue.setText("Bienvenue TheRainb0w, sur votre compte MelySIG !");

        monLabelActualiteSelectionne.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        monLabelActualiteSelectionne.setForeground(new java.awt.Color(255, 255, 255));
        monLabelActualiteSelectionne.setText("Votre actualité en détail :");

        maListeActualites.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        maListeActualites.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Nouveau thème en place !", "Et un parcours de plus héhé", "Découvrez ce super POI !", "Les prostitués ont aussi leurs place dans notre base :-o", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        maListeActualites.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        maListeActualites.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        maListeActualites.setSelectionBackground(new java.awt.Color(0, 0, 0));
        monPanelDefilantActualites.setViewportView(maListeActualites);

        monLabelDernieresActualites.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        monLabelDernieresActualites.setForeground(new java.awt.Color(255, 255, 255));
        monLabelDernieresActualites.setText("Voici les dernières actualités :");

        maDescriptionActualite.setColumns(20);
        maDescriptionActualite.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        maDescriptionActualite.setRows(5);
        maDescriptionActualite.setText("Le thème Restauration est désormais disponible,\nVous êtes un fin gourmet ?\nSa tombe bien on va pouvoir se remplir le bidon ensemble!\nChoisissez du Kebab le plus proche au restaurant étoilé :-)");
        maDescriptionActualite.setWrapStyleWord(true);
        maDescriptionActualite.setName(""); // NOI18N
        monPanelDefilantDescriptionActualite.setViewportView(maDescriptionActualite);

        monLibelleActualite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monLibelleActualite.setText("Nouveau thème en place !");

        monBoutonModifier.setText("Modifier");

        monBoutonAjouter.setText("Ajouter");

        monBoutonSupprimer.setText("Supprimer");

        monLabelStatistiques.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monLabelStatistiques.setForeground(new java.awt.Color(255, 255, 255));
        monLabelStatistiques.setText("Statistiques:");

        mesStatistiques.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mesStatistiques.setForeground(new java.awt.Color(255, 255, 255));
        mesStatistiques.setText("52 Points d'intérêts, 21 Parcours, 5 Thèmes, 10 Actualités, 19 Utilisateurs & 1 Carte.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Découvrez les dernières nouveautés de notre base :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Les derniers POIs :");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Musée Lorrain", "Musée des beaux-arts", "Musée de l'École de Nancy", "MacDonald", "Made In France", "Quick", "UGC", "KinePolis", "Caméo" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFixedCellWidth(160);
        jList1.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jList1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Les derniers Parcours :");

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "TheRainb0w", "Coonax", "Poook", "Ezio", "Edge", "Psycho", "Paco", "Blondie", "Shinn", "BenPD", "Panzer", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList2.setFixedCellWidth(80);
        jList2.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jList2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Les derniers Utilisateurs :");

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Musées de Nancy", "FastFood de Nancy", "Commerces de Nancy", "Marché de Noël de Strasboug", "Fleuristes de Thionville", "Pompes Funèvres d'Epinal", "Prostituées de Nancy", "Garagistes de Metz", "Plombiers de Vandoeuvre", "Escort-Girls du Luxembourg", "Stations Essences de Tomblaine" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList3.setFixedCellHeight(16);
        jList3.setFixedCellWidth(160);
        jList3.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jList3.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jList3);

        jButton1.setText("Déconnexion de mon espace");

        jButton2.setText("Consulter la base de données");

        javax.swing.GroupLayout panelContenuLayout = new javax.swing.GroupLayout(panelContenu);
        panelContenu.setLayout(panelContenuLayout);
        panelContenuLayout.setHorizontalGroup(
            panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenuLayout.createSequentialGroup()
                .addGroup(panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelContenuLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(monLabelStatistiques)
                        .addGap(44, 44, 44)
                        .addComponent(mesStatistiques, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(monPanelDefilantActualites, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(monTexteDeBienvenue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                .addGroup(panelContenuLayout.createSequentialGroup()
                                    .addComponent(monBoutonModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(monBoutonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(monBoutonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(monPanelDefilantDescriptionActualite)
                                .addComponent(monLibelleActualite, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(monLabelActualiteSelectionne, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monLabelDernieresActualites, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenuLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelContenuLayout.setVerticalGroup(
            panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenuLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monLabelStatistiques, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mesStatistiques, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(monTexteDeBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monLabelDernieresActualites, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addGroup(panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenuLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenuLayout.createSequentialGroup()
                        .addComponent(monPanelDefilantActualites, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monLabelActualiteSelectionne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monLibelleActualite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monPanelDefilantDescriptionActualite, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelContenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monBoutonModifier)
                            .addComponent(monBoutonAjouter)
                            .addComponent(monBoutonSupprimer))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(panelContenu);
        panelContenu.setBounds(0, 70, 900, 640);

        panelFond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/melysig/images/worldSIG.png"))); // NOI18N
        panelFond.setToolTipText("");
        panelFond.setMaximumSize(new java.awt.Dimension(900, 700));
        panelFond.setPreferredSize(new java.awt.Dimension(900, 700));
        getContentPane().add(panelFond);
        panelFond.setBounds(0, 70, 900, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualitesNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualitesNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualitesNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualitesNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualitesNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea maDescriptionActualite;
    private javax.swing.JList maListeActualites;
    private javax.swing.JLabel mesStatistiques;
    private javax.swing.JButton monBoutonAjouter;
    private javax.swing.JButton monBoutonModifier;
    private javax.swing.JButton monBoutonSupprimer;
    private javax.swing.JLabel monLabelActualiteSelectionne;
    private javax.swing.JLabel monLabelDernieresActualites;
    private javax.swing.JLabel monLabelStatistiques;
    private javax.swing.JTextField monLibelleActualite;
    private javax.swing.JScrollPane monPanelDefilantActualites;
    private javax.swing.JScrollPane monPanelDefilantDescriptionActualite;
    private javax.swing.JLabel monTexteDeBienvenue;
    private javax.swing.JPanel panelContenu;
    private javax.swing.JLabel panelFond;
    private javax.swing.JPanel panelHaut;
    // End of variables declaration//GEN-END:variables
}
