/*
 * MelySig - Geolocalisation de points d'interets sur vos endroits favoris !
 * MelySig est systeme d'information geographique qui animera vos decouvertes du monde :)
 * Copyright 2014 - melysig.exia-nancy.com
 * Auteurs : Pocecco Julien, Mougenel Gerold, Gaudenot Guillaume & Robert Sebastien.
 */

package fr.melysig.vues;

import fr.melysig.main.MVC;
import fr.melysig.models.Lieux;
import fr.melysig.models.ListLieux;
import fr.melysig.models.ListThemes;
import fr.melysig.models.Themes;
import fr.melysig.process.LieuProcess;
import fr.melysig.process.ThemeProcess;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Classe de vue d'<b>edition/ajout/suppresion des thèmes, lieux et utilisateurs</b>
 * Permet d'afficher et manipuler les thèmes/lieux et utilisateurs via une IHM
 *
 * @author Guillaume G.
 * @since 0.4
 * @version 0.1
 */

public class EditionVue extends javax.swing.JDialog implements Observer{

    private ListThemes listThemes;
    private ListLieux listLieu;
    private Themes currentThemes;
    private Lieux currentLieu;
    private EditionVue editionVue; 
    
    /**
     * Creates new form EditionVue
     */
    public EditionVue(JFrame consulteVue, ListLieux lieu, ListThemes themes) {
        
      
        super(consulteVue, Dialog.ModalityType.APPLICATION_MODAL);
        this.editionVue = this;
        listThemes = themes;
        listThemes.addObserver(this.editionVue);
        listLieu =lieu;
        listLieu.addObserver(this.editionVue);
        initComponents();
        update(listThemes, null);
        update(listLieu, null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//
    private void initComponents() {

        PanelHeader = new javax.swing.JPanel();
        logoConnexionUtilisateur = new javax.swing.JLabel();
        JTabbedPaneEdition = new javax.swing.JTabbedPane();
        PanelTheme = new javax.swing.JPanel();
        labelSelectionTheme = new javax.swing.JLabel();
        ComboboxSelectionTheme = new javax.swing.JComboBox();
        separateurTheme = new javax.swing.JSeparator();
        labelModificationTheme = new javax.swing.JLabel();
        labelLibelleTheme = new javax.swing.JLabel();
        boutonSupprimerThemeSelectionner = new javax.swing.JButton();
        txtLibelleTheme = new javax.swing.JTextField();
        labelDescriptionTheme = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescriptionTheme = new javax.swing.JTextArea();
        boutonModifierTheme = new javax.swing.JButton();
        separateurTheme2 = new javax.swing.JSeparator();
        labelAjoutTheme = new javax.swing.JLabel();
        labelLibelleAjoutTheme = new javax.swing.JLabel();
        labelDescriptionAjoutTheme = new javax.swing.JLabel();
        txtAjoutLibelleTheme = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAjouterDescriptionTheme = new javax.swing.JTextArea();
        boutonAjouterTheme = new javax.swing.JButton();
        PanelLieux = new javax.swing.JPanel();
        separateurLieu = new javax.swing.JSeparator();
        labelSelectionLieux = new javax.swing.JLabel();
        ComboboxSelectionLieux = new javax.swing.JComboBox();
        boutonSupprimerLieuSelectionner = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelNomLieu = new javax.swing.JLabel();
        txtNomLieu = new javax.swing.JTextField();
        labelCarteLieu = new javax.swing.JLabel();
        txtCarteLieu = new javax.swing.JTextField();
        boutonUploaderImageCarteLieu = new javax.swing.JButton();
        labelDescriptionLieu = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescriptionLieu = new javax.swing.JTextArea();
        separateurLieu2 = new javax.swing.JSeparator();
        boutonModifierLieu = new javax.swing.JButton();
        labelNouveauLieu = new javax.swing.JLabel();
        labelAJoutNomLieu = new javax.swing.JLabel();
        labelAjoutCarteLieu = new javax.swing.JLabel();
        labelAjoutDescriptionLieu = new javax.swing.JLabel();
        txtAjoutNomLieu = new javax.swing.JTextField();
        txtAjoutCarteLieu = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAJoutDescriptionLieu = new javax.swing.JTextArea();
        boutonAjouterLieu = new javax.swing.JButton();
        boutonAjoutUploaderImageCarteLieu = new javax.swing.JButton();
        PanelUtilisateur = new javax.swing.JPanel();
        labelVotreCompteMelySIG = new javax.swing.JLabel();
        labelPseudoUtilisateur = new javax.swing.JLabel();
        txtPseudoUtilisateur = new javax.swing.JTextField();
        labelNomUtilisateur = new javax.swing.JLabel();
        labelPrenomUtilisateur = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        txtNomUtilisateur = new javax.swing.JTextField();
        txtPrenomUtilisateur = new javax.swing.JTextField();
        labelEmailUtilisateur = new javax.swing.JLabel();
        txtEmailUtilisateur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelHeader.setBackground(new java.awt.Color(204, 255, 102));

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoConnexionUtilisateur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoConnexionUtilisateur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelSelectionTheme.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelSelectionTheme.setText("Sélection :");

        ComboboxSelectionTheme.setModel(new javax.swing.DefaultComboBoxModel());
        ComboboxSelectionTheme.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent ie) {
                if(ie.getStateChange()==ItemEvent.SELECTED){
                currentThemes = ThemeProcess.getInstance().chargerThemes((String) ie.getItem());
                displayThemes(currentThemes);
                }
            }
        }) ;

        labelModificationTheme.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelModificationTheme.setText("Modification");

        labelLibelleTheme.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelLibelleTheme.setText("Libelle :");

        boutonSupprimerThemeSelectionner.setText("Supprimer");
        boutonSupprimerThemeSelectionner.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                //Supprimer l'ancien theme
                listThemes.delete(currentThemes);
                ThemeProcess.getInstance().effacerThemes(currentThemes);
                currentThemes=null;
                listThemes.notifyObservers();
                JOptionPane.showMessageDialog(editionVue, "Votre thème a bien été supprimé");
                
            }
        });

        labelDescriptionTheme.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelDescriptionTheme.setText("Description :");

        txtDescriptionTheme.setColumns(20);
        txtDescriptionTheme.setRows(5);
        txtDescriptionTheme.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(txtDescriptionTheme);

        boutonModifierTheme.setText("Modifier");
        boutonModifierTheme.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                //mise à jour objet memoire
                currentThemes.setDescription(txtDescriptionTheme.getText());
                currentThemes.setLibelle(txtLibelleTheme.getText());
                
                //mise à jour en base de donnée
                currentThemes = ThemeProcess.getInstance().mettreAjourThemes(currentThemes);
                
                //On force la mise à jour de la combobox
                String monTheme = currentThemes.getLibelle();
                listThemes.update();
                ComboboxSelectionTheme.getModel().setSelectedItem(monTheme);
                JOptionPane.showMessageDialog(editionVue, "Votre thème a bien été modifié");
               
                
            }
        });
        

        labelAjoutTheme.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelAjoutTheme.setText("Nouveau");

        labelLibelleAjoutTheme.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelLibelleAjoutTheme.setText("Libelle :");

        labelDescriptionAjoutTheme.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelDescriptionAjoutTheme.setText("Description :");

        txtAjouterDescriptionTheme.setColumns(20);
        txtAjouterDescriptionTheme.setRows(5);
        jScrollPane2.setViewportView(txtAjouterDescriptionTheme);

        boutonAjouterTheme.setText("Ajouter");
        boutonAjouterTheme.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                 currentThemes = ThemeProcess.getInstance().creerTheme(txtAjoutLibelleTheme.getText(), txtAjouterDescriptionTheme.getText());
                 listThemes.add(currentThemes);
                 String monTheme = currentThemes.getLibelle();
                 listThemes.notifyObservers();
                 ComboboxSelectionTheme.getModel().setSelectedItem(monTheme);
                 txtAjoutLibelleTheme.setText("");
                 txtAjouterDescriptionTheme.setText("");
                 JOptionPane.showMessageDialog(editionVue, "Votre thème a bien été ajouté");
            }
        });

        javax.swing.GroupLayout PanelThemeLayout = new javax.swing.GroupLayout(PanelTheme);
        PanelTheme.setLayout(PanelThemeLayout);
        PanelThemeLayout.setHorizontalGroup(
            PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelThemeLayout.createSequentialGroup()
                .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelThemeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separateurTheme, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelThemeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(boutonSupprimerThemeSelectionner))
                            .addGroup(PanelThemeLayout.createSequentialGroup()
                                .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLibelleTheme)
                                    .addGroup(PanelThemeLayout.createSequentialGroup()
                                        .addComponent(labelSelectionTheme)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboboxSelectionTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelThemeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelDescriptionTheme)
                        .addGap(18, 18, 18)
                        .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(PanelThemeLayout.createSequentialGroup()
                                .addComponent(txtLibelleTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelThemeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separateurTheme2))
                    .addGroup(PanelThemeLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(labelAjoutTheme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boutonAjouterTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelThemeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelThemeLayout.createSequentialGroup()
                                .addComponent(labelLibelleAjoutTheme)
                                .addGap(47, 47, 47)
                                .addComponent(txtAjoutLibelleTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelThemeLayout.createSequentialGroup()
                                .addComponent(labelDescriptionAjoutTheme)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelThemeLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(labelModificationTheme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(boutonModifierTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelThemeLayout.setVerticalGroup(
            PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelThemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelThemeLayout.createSequentialGroup()
                        .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSelectionTheme)
                            .addComponent(ComboboxSelectionTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutonSupprimerThemeSelectionner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separateurTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelModificationTheme))
                    .addComponent(boutonModifierTheme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLibelleTheme)
                    .addComponent(txtLibelleTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelThemeLayout.createSequentialGroup()
                        .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescriptionTheme)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(separateurTheme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAjoutTheme))
                    .addComponent(boutonAjouterTheme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLibelleAjoutTheme)
                    .addComponent(txtAjoutLibelleTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescriptionAjoutTheme)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        JTabbedPaneEdition.addTab("Themes", PanelTheme);

        labelSelectionLieux.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelSelectionLieux.setText("Sélection :");

        ComboboxSelectionLieux.setModel(new javax.swing.DefaultComboBoxModel());
        ComboboxSelectionLieux.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent ie) {
               if(ie.getStateChange()==ItemEvent.SELECTED){
                currentLieu = LieuProcess.getInstance().chargerLieux((String) ie.getItem());
                displayLieu(currentLieu);
               }
            }
        });
        boutonSupprimerLieuSelectionner.setText("Supprimer");
        boutonSupprimerLieuSelectionner.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                //Supprimer l'ancien lieu
                listLieu.delete(currentLieu);
                LieuProcess.getInstance().effacerLieu(currentLieu);
                currentLieu=null;
                listLieu.notifyObservers();
                JOptionPane.showMessageDialog(editionVue, "Votre lieu a bien été supprimé");
                
            }
        });
        
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Modification");

        labelNomLieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelNomLieu.setText("Nom :");

        labelCarteLieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelCarteLieu.setText("Carte :");

        boutonUploaderImageCarteLieu.setText("Uploader une image");
        boutonUploaderImageCarteLieu.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                try {
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.showOpenDialog(editionVue);
                    File file = fileChooser.getSelectedFile();
                    if(file != null){
                        txtCarteLieu.setText( file.getCanonicalPath().replaceAll("\\\\", "/"));
                    }
                } catch (IOException ex) {
                    Logger.getLogger(EditionVue.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        labelDescriptionLieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelDescriptionLieu.setText("Description :");

        txtDescriptionLieu.setColumns(20);
        txtDescriptionLieu.setRows(5);
        jScrollPane3.setViewportView(txtDescriptionLieu);

        boutonModifierLieu.setText("Modifier");
        boutonModifierLieu.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                //mise à jour objet memoire
                currentLieu.setDescription(txtDescriptionLieu.getText());
                currentLieu.setNom(txtNomLieu.getText());
                currentLieu.setCarte((txtCarteLieu.getText() != null) ? txtCarteLieu.getText().replaceAll("\\\\","/") : "");
                
                //mise à jour en base de donnée
                currentLieu = LieuProcess.getInstance().mettreAjourLieu(currentLieu);
                
                //On force la mise à jour de la combobox
                String monLieu = currentLieu.getNom();
                listLieu.update();
                ComboboxSelectionLieux.getModel().setSelectedItem(monLieu);
                JOptionPane.showMessageDialog(editionVue, "Votre lieu a bien été modifié");
               
                
            }
        });

        labelNouveauLieu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelNouveauLieu.setText("Nouveau");

        labelAJoutNomLieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelAJoutNomLieu.setText("Nom :");

        labelAjoutCarteLieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelAjoutCarteLieu.setText("Carte :");

        labelAjoutDescriptionLieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelAjoutDescriptionLieu.setText("Description :");

        txtAJoutDescriptionLieu.setColumns(20);
        txtAJoutDescriptionLieu.setRows(5);
        jScrollPane4.setViewportView(txtAJoutDescriptionLieu);

        boutonAjouterLieu.setText("Ajouter");
        boutonAjouterLieu.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                String nom = txtAjoutNomLieu.getText();
                String carte = txtAjoutCarteLieu.getText() != null ?  txtAjoutCarteLieu.getText().replaceAll("\\\\", "/") : "";
                String description = txtAJoutDescriptionLieu.getText();
                int utilisateur = MVC.obtenirMVC().monControleurUtilisateur.getId();
                currentLieu = LieuProcess.getInstance().creerLieux(nom, carte ,description,utilisateur );
                 listLieu.add(currentLieu);
                 String monLieu = currentLieu.getNom();
                 listLieu.notifyObservers();
                 ComboboxSelectionLieux.getModel().setSelectedItem(monLieu);
                 txtAjoutNomLieu.setText("");
                 txtAJoutDescriptionLieu.setText("");
                 txtAjoutCarteLieu.setText("");
                 JOptionPane.showMessageDialog(editionVue, "Votre Lieu a bien été ajouté");
            }
        });
        boutonAjoutUploaderImageCarteLieu.setText("Uploader une image");
        boutonAjoutUploaderImageCarteLieu.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                try {
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.showOpenDialog(editionVue);
                    File path = fileChooser.getSelectedFile();
                    if(path != null){
                        txtAjoutCarteLieu.setText( path.getCanonicalPath().replaceAll("\\\\", "/"));
                    }
                } catch (IOException ex) {
                    Logger.getLogger(EditionVue.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout PanelLieuxLayout = new javax.swing.GroupLayout(PanelLieux);
        PanelLieux.setLayout(PanelLieuxLayout);
        PanelLieuxLayout.setHorizontalGroup(
            PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLieuxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separateurLieu2)
                    .addGroup(PanelLieuxLayout.createSequentialGroup()
                        .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separateurLieu)
                            .addGroup(PanelLieuxLayout.createSequentialGroup()
                                .addComponent(labelSelectionLieux)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboboxSelectionLieux, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boutonSupprimerLieuSelectionner))
                            .addGroup(PanelLieuxLayout.createSequentialGroup()
                                .addComponent(labelDescriptionLieu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLieuxLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(213, 213, 213)
                                .addComponent(boutonModifierLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLieuxLayout.createSequentialGroup()
                                .addComponent(labelAjoutDescriptionLieu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4)))
                        .addContainerGap())))
            .addGroup(PanelLieuxLayout.createSequentialGroup()
                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLieuxLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNouveauLieu)
                        .addGap(229, 229, 229))
                    .addGroup(PanelLieuxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLieuxLayout.createSequentialGroup()
                                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCarteLieu)
                                    .addComponent(labelNomLieu))
                                .addGap(44, 44, 44)
                                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelLieuxLayout.createSequentialGroup()
                                        .addComponent(txtCarteLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boutonUploaderImageCarteLieu))))
                            .addGroup(PanelLieuxLayout.createSequentialGroup()
                                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAjoutCarteLieu)
                                    .addComponent(labelAJoutNomLieu))
                                .addGap(48, 48, 48)
                                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAjoutNomLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtAjoutCarteLieu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boutonAjoutUploaderImageCarteLieu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)))
                .addComponent(boutonAjouterLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelLieuxLayout.setVerticalGroup(
            PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLieuxLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLieuxLayout.createSequentialGroup()
                        .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelLieuxLayout.createSequentialGroup()
                                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelSelectionLieux)
                                    .addComponent(ComboboxSelectionLieux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boutonSupprimerLieuSelectionner))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separateurLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(boutonModifierLieu))
                        .addGap(24, 24, 24)
                        .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNomLieu)
                            .addComponent(txtNomLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCarteLieu)
                            .addComponent(txtCarteLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutonUploaderImageCarteLieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescriptionLieu)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(separateurLieu2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNouveauLieu)
                            .addComponent(boutonAjouterLieu))
                        .addGap(24, 24, 24))
                    .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAjoutNomLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelAJoutNomLieu)))
                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAjoutCarteLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAjoutCarteLieu)
                    .addComponent(boutonAjoutUploaderImageCarteLieu))
                .addGap(15, 15, 15)
                .addGroup(PanelLieuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAjoutDescriptionLieu)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        JTabbedPaneEdition.addTab("Lieux", PanelLieux);

        labelVotreCompteMelySIG.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelVotreCompteMelySIG.setText("Votre compte MelySIG");

        labelPseudoUtilisateur.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelPseudoUtilisateur.setText("Pseudo :");

        labelNomUtilisateur.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelNomUtilisateur.setText("Nom :");

        labelPrenomUtilisateur.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelPrenomUtilisateur.setText("Prénom :");

        jButton2.setText("Modifier");

        labelEmailUtilisateur.setText("Email :");

        javax.swing.GroupLayout PanelUtilisateurLayout = new javax.swing.GroupLayout(PanelUtilisateur);
        PanelUtilisateur.setLayout(PanelUtilisateurLayout);
        PanelUtilisateurLayout.setHorizontalGroup(
            PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                        .addComponent(labelPseudoUtilisateur)
                        .addGap(18, 18, 18)
                        .addComponent(txtPseudoUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                        .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                                    .addComponent(labelNomUtilisateur)
                                    .addGap(34, 34, 34)
                                    .addComponent(txtNomUtilisateur)
                                    .addGap(272, 272, 272))
                                .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                                    .addComponent(labelPrenomUtilisateur)
                                    .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                                            .addGap(237, 237, 237)
                                            .addComponent(labelVotreCompteMelySIG))
                                        .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPrenomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtEmailUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(labelEmailUtilisateur))
                        .addGap(0, 300, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelUtilisateurLayout.setVerticalGroup(
            PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVotreCompteMelySIG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPseudoUtilisateur)
                            .addComponent(txtPseudoUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelUtilisateurLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomUtilisateur)
                    .addComponent(txtNomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrenomUtilisateur)
                    .addComponent(txtPrenomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmailUtilisateur)
                    .addComponent(txtEmailUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        JTabbedPaneEdition.addTab("Utilisateur", PanelUtilisateur);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JTabbedPaneEdition)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTabbedPaneEdition)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void boutonModifierLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonModifierLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonModifierLieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditionVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditionVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditionVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditionVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditionVue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//
    private javax.swing.JComboBox ComboboxSelectionLieux;
    private javax.swing.JComboBox ComboboxSelectionTheme;
    private javax.swing.JTabbedPane JTabbedPaneEdition;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelLieux;
    private javax.swing.JPanel PanelTheme;
    private javax.swing.JPanel PanelUtilisateur;
    private javax.swing.JButton boutonAjouterLieu;
    private javax.swing.JButton boutonAjouterTheme;
    private javax.swing.JButton boutonModifierLieu;
    private javax.swing.JButton boutonModifierTheme;
    private javax.swing.JButton boutonSupprimerLieuSelectionner;
    private javax.swing.JButton boutonSupprimerThemeSelectionner;
    private javax.swing.JButton boutonUploaderImageCarteLieu;
    private javax.swing.JButton boutonAjoutUploaderImageCarteLieu;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtDescriptionTheme;
    private javax.swing.JTextArea txtAjouterDescriptionTheme;
    private javax.swing.JLabel labelAJoutNomLieu;
    private javax.swing.JLabel labelAjoutCarteLieu;
    private javax.swing.JLabel labelAjoutDescriptionLieu;
    private javax.swing.JLabel labelAjoutTheme;
    private javax.swing.JLabel labelCarteLieu;
    private javax.swing.JLabel labelDescriptionAjoutTheme;
    private javax.swing.JLabel labelDescriptionLieu;
    private javax.swing.JLabel labelDescriptionTheme;
    private javax.swing.JLabel labelEmailUtilisateur;
    private javax.swing.JLabel labelLibelleAjoutTheme;
    private javax.swing.JLabel labelLibelleTheme;
    private javax.swing.JLabel labelModificationTheme;
    private javax.swing.JLabel labelNomLieu;
    private javax.swing.JLabel labelNomUtilisateur;
    private javax.swing.JLabel labelNouveauLieu;
    private javax.swing.JLabel labelPrenomUtilisateur;
    private javax.swing.JLabel labelPseudoUtilisateur;
    private javax.swing.JLabel labelSelectionLieux;
    private javax.swing.JLabel labelSelectionTheme;
    private javax.swing.JLabel labelVotreCompteMelySIG;
    private javax.swing.JLabel logoConnexionUtilisateur;
    private javax.swing.JSeparator separateurLieu;
    private javax.swing.JSeparator separateurLieu2;
    private javax.swing.JSeparator separateurTheme;
    private javax.swing.JSeparator separateurTheme2;
    private javax.swing.JTextArea txtAJoutDescriptionLieu;
    private javax.swing.JTextField txtAjoutCarteLieu;
    private javax.swing.JTextField txtAjoutLibelleTheme;
    private javax.swing.JTextField txtAjoutNomLieu;
    private javax.swing.JTextField txtCarteLieu;
    private javax.swing.JTextArea txtDescriptionLieu;
    private javax.swing.JTextField txtEmailUtilisateur;
    private javax.swing.JTextField txtLibelleTheme;
    private javax.swing.JTextField txtNomLieu;
    private javax.swing.JTextField txtNomUtilisateur;
    private javax.swing.JTextField txtPrenomUtilisateur;
    private javax.swing.JTextField txtPseudoUtilisateur;
    // End of variables declaration                   

    @Override
    public void update(Observable o, Object o1) {
        if(o instanceof ListThemes){
             // clear de la comboBox
            ((DefaultComboBoxModel)ComboboxSelectionTheme.getModel()).removeAllElements();  
            // list tous les themes et l'ajoute dans la combo box
            for (Themes theme : ((ListThemes)o).getList()){
                ComboboxSelectionTheme.addItem(theme.getLibelle());
            }
        } else if (o instanceof ListLieux){
            // clear de la comboBox
            ((DefaultComboBoxModel)ComboboxSelectionLieux.getModel()).removeAllElements();  
            // list tous les themes et l'ajoute dans la combo box
            for (Lieux lieu : ((ListLieux)o).getList()){
                ComboboxSelectionLieux.addItem(lieu.getNom());
            }
        }
    }
    protected void displayThemes(Themes themes){
        txtLibelleTheme.setText(themes.getLibelle());
        txtDescriptionTheme.setText(themes.getDescription());
    }
    
    protected void displayLieu(Lieux lieu){
        txtNomLieu.setText(lieu.getNom());
        txtDescriptionLieu.setText(lieu.getDescription());
        txtCarteLieu.setText(lieu.getCarte());
    }
 }
